name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: alexandregv/norminette-action@v3
      with:
        flags: 'srcs includes'
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build application
      run: make all
